name = "InteractiveDynamics"
uuid = "ec714cd0-5f51-11eb-0b6e-452e7367ff84"
repo = "https://github.com/JuliaDynamics/InteractiveDynamics.jl.git"
version = "0.14.1"

[deps]
AbstractPlotting = "537997a7-5e4e-5d89-9595-2241ea00577e"
DataStructures = "864edb3b-99cc-5e75-8d2d-829cb0a9cfe8"
Observables = "510215fc-4207-5dde-b226-833fc4488ee2"
Requires = "ae029012-a4dd-5104-9daa-d747884805df"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[compat]
AbstractPlotting = "0.15, 0.16"
DataStructures = "0.17, 0.18"
Observables = "0.2, 0.3, 0.4"
Requires = "1"
StatsBase = "0.32.0, 0.33"
julia = "1.0"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
